apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-knote-app
spec:
  strategy: 
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      app: my-app1
  template:
    metadata:
      labels:
        app: my-app1 
    spec:
      containers:
        - name: my-knote
          image: devopstrainingschool/java-nodejs-jenkins
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://my-db-service:27017/dev
        
          imagePullPolicy: Always
