apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-knote-app
spec:
  strategy: 
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app 
    spec:
      containers:
        - name: my-knote
          image: devopstrainingschool/knote-jenkins:67
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
        
          imagePullPolicy: Always
